# wrangler.toml
name = 'proxy-replicator'
main = "src/index.js"
compatibility_date = "2026-04-07"

workers_dev = true

[vars]
PRIMARY_URL = "https://www.someecards.com"
SECONDARY_URL = "https://www-cf.someecards.com"
